@EndUserText.label: 'Service defination for Travel'
define service ZRT_UI_RAP_TRAV_SD_01 {
  expose ZCRT_RAP_TRAV_01 as Travel;
  expose zcrt_rap_booking_01 as Booking;
  expose /DMO/I_Agency as Agency;
  expose /DMO/I_Customer as Customer;
  expose /DMO/I_Flight as Flight;
  expose /DMO/I_Carrier as Carrier;
  expose /DMO/I_Connection as Connection;
  expose /DMO/I_Airport as Airport;
  expose I_Currency as Currency;
  expose I_Country as Country;
}
